version: "3.9"

services:
  nginx:
    image: nginx:alpine
    container_name: reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - vite-v2
      - react-v1
      - api-v1
    restart: unless-stopped

  vite-v2:
    build: ./v2_frontend
    container_name: vite-v2
    restart: unless-stopped

  react-v1:
    build: ./v1_frontend
    container_name: react-v1
    restart: unless-stopped

  api-v1:
    build: ./v1_backend
    container_name: api-v1
    restart: unless-stopped
